### ISSUE TITLE
Exception starting session

### ISSUE THREAD

**Issue by thebeekeeper** [thebeekeeper/Laurus.UiTest#31]
Using VS2015 + xUnit.net adapter:

{"Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Laurus.UiTest.ControlRegistry.Laurus.UiTest.IControlRegistry.RegisterLocalControls()
   at Laurus.UiTest.Selenium.SeleniumTest..ctor(Dictionary`2 parameters, StartupParameters startupParams, Func`2 mapSelector) in e:\TeamCity\buildAgent\work\db6155dd349951ec\Laurus.UiTest.Selenium\SeleniumTest.cs:line 54
   at Laurus.UiTest.Selenium.SeleniumTestBuilder.UsingSeleniumRemote(TestBuilder builder, String remoteHost) in e:\TeamCity\buildAgent\work\db6155dd349951ec\Laurus.UiTest.Selenium\SeleniumTestBuilder.cs:line 30

**Comment by thebeekeeper** [comment]
Workaround is to copy Microsoft.VisualStudio.TestPlatform.ObjectModel.dll into bin dir
